### ISSUE TITLE
Retroactively awarding titles

### ISSUE THREAD

**Issue by faeldray** [Aurilux/Titles#11]
I added this mod to an existing save and noticed that I didn't have any titles for achievements I had already done (make iron tools, tame an animal, etc.). Would it be possible to add those titles retroactively somehow?

This is a fantastic mod by the way, perfect for a medieval fantasy modpack!

**Comment by Aurilux** [comment]
Thanks! I'll look into it.

For the moment, you can use the "/titles add <player> <titleKey>" command to give you titles for the advancements you have.
