### ISSUE TITLE
Crash: Error executing task

### ISSUE THREAD

**Issue by faeldray** [Aurilux/Titles#13]
I keep experiencing this error while I'm playing (luckily VanillaFix prevents it from interrupting the game). It seems to occur when I get an achievement that does not have a Title attached to it (I think only for achievements added by mods).

https://pastebin.com/T6m8QBYf

**Comment by Aurilux** [comment]
It was caused by a mod not sticking to the traditional advancement .lang key pattern (i.e. advancement.titles.root). Can identify the mod that caused this (most likely the one with the advancement you tried to get as it error'ed), so I can test my fix and make sure it works?

**Comment by faeldray** [comment]
I checked my logs and it looks to be Electroblob's Wizardry.
