### ISSUE TITLE
Probably User error

### ISSUE THREAD

**Issue by mistaboom** [Aurilux/Titles#18]
I'm on minecraft 1.12.2
I'm a modpack maker. I created the .json for my titles but I still can't give myself them through commands. Do I need to put the code
TitlesAPI.registerTitle(<modid>:<advancementId>, TitleInfo.TitleRarity.<rarity>)
in a zenscript or something first? it's asking for a mod ID too. I don't have a mod. I was going to use FTB quests to give the title. Is that it wants?
Help would be greatly appreciated.

**Comment by Aurilux** [comment]
If you haven't yet, take a look at the wiki I made here on github. If that doesn't help, feel free to hop on the discord (you can find the link in any of my projects on curseforge). There are a number of people going through the same thing you are, so they might be able to help, and it will be easier to chat there as well.
