### ISSUE TITLE
Cannot find loot_titles.json

### ISSUE THREAD

**Issue by XdLReaper** [Aurilux/Titles#19]
I wanted to make a custom title (for a modpack) on the 1.16 version of the mod. I went to the wiki to see how but didn't manage to find the loot_titles.json file. I searched everywhere for the file but to no avail.

**Comment by Aurilux** [comment]
https://github.com/Aurilux/Titles/blob/master/src/main/resources/data/titles/loot_titles.json

**Comment by XdLReaper** [comment]
Thanks!
