### ISSUE TITLE
Modded Advancements?

### ISSUE THREAD

**Issue by beanaboston** [Aurilux/Titles#2]
I'm curious if you have any support for mod advancements or if there was a way you could allow people to make new titles for mod advancements.

**Comment by Aurilux** [comment]
I do! If you take a look at the description on the main page, it explains everything including how to add your own titles to mods.

**Comment by beanaboston** [comment]
Oh huh. I guess I missed that. Thanks for letting me know!

**Comment by Aurilux** [comment]
Lol, np XD
