### ISSUE TITLE
Nonrandom way to gain loot titles?

### ISSUE THREAD

**Issue by XdLReaper** [Aurilux/Titles#20]
Is there a way to gain loot titles without the title scrolls or the "titles add" command which doesn't seem to work with any of the titles in loot_titles.json? Also thanks for your time!

**Comment by Aurilux** [comment]
Huh, seems you can't add loot titles via command. I'll put it on my todo list for the next update, which will include an easier way for other to add titles as well.

**Comment by XdLReaper** [comment]
Looking forward to it! Thanks!
