### ISSUE TITLE
Dedicated Server Crash

### ISSUE THREAD

**Issue by DaddyP1G** [Aurilux/Titles#21]
Launches fine.  Actually worked for 30 minutes, multiple people applied Titles.  When i dropped a campfire, server crashed 

https://gist.github.com/DaddyP1G/b706cda002eda9075914f1ff137b2545

**Comment by Aurilux** [comment]
Huh, that's so weird. I'll take a look at it this weekend.

**Comment by DaddyP1G** [comment]
Yes, it worked fine for awhile.   Even after the error, the server would launch fine, but then crash whenever someone logged in.
