### ISSUE TITLE
Can't find data/titles/titles folder in modpack.

### ISSUE THREAD

**Issue by xXDrTangerineXx** [Aurilux/Titles#25]
I'm trying to find the folder to make custom titles for my modpack and am unable to locate it. I installed the mod through the curse launcher if that makes any difference.

**Comment by Aurilux** [comment]
Which version of the mod are you using (1.12 or 1.16)?

**Comment by xXDrTangerineXx** [comment]
I'm using 1.16

**Comment by Aurilux** [comment]
https://github.com/Aurilux/Titles/tree/master/src/main/resources/data/titles/titles

**Comment by xXDrTangerineXx** [comment]
Just so i don't put them in the wrong place, what is the file path to put them in?

**Comment by Aurilux** [comment]
You'll need to make a data pack to override the default values provided by the mod. You can find most information [here](https://minecraft.fandom.com/wiki/Data_Pack).

**Comment by xXDrTangerineXx** [comment]
Thank you for the help.

**Comment by Aurilux** [comment]
No problem. If you have any further questions, feel free to post in my discord. You can find the link in any of the mod descriptions on Curseforge.
