### ISSUE TITLE
Cant make custom titles?

### ISSUE THREAD

**Issue by BlueYoshi68** [Aurilux/Titles#27]
I was looking at the wiki, and it says that a titles.json file should exist, but I don't see a single thing named that. And if you're meant to add it yourself, it doesn't say WHERE to add it.

**Comment by Aurilux** [comment]
Which version of Minecraft are you using?

**Comment by BlueYoshi68** [comment]
1.16

**Comment by Aurilux** [comment]
Just updated the wiki under Modpack Makers to make it more clear. If this provides the info you needed, feel free to close this issue.
