### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Gamerbolts** [Aurilux/Titles#3]
Hi!

I am creating a modpack and while going around testing I crashed, seems to be this mod. I noticed before I crashed I obtained an achievement "Stone Age" I was in creative and middle mouse clicked a block.

Here is the crashlog
https://pastebin.com/ZXvLXSTm

Any help is appreciated! Thank you.

**Comment by Aurilux** [comment]
I've identified the problem. It'll be fixed in the next update, hopefully in the next day or two.
