### ISSUE TITLE
Titles not applied in latest version

### ISSUE THREAD

**Issue by SuperTiru** [Aurilux/Titles#32]
I am currently using 1.16.5 forge and 3.3.2 version of that mod.
I'm playing the single world.
There is a problem with the title not being applied in a later version.

_*I'm sorry for my poor English. My native language is not English._

**Comment by Aurilux** [comment]
The most recent version for 1.16 is 3.4.2. Download and install the updated version and let me know if that solves your problem.

**Comment by SuperTiru** [comment]
I'm sorry I'm late. Yes, the problem still occurs. Versions above 3.3.2 still do not have a title.

**Comment by Aurilux** [comment]
Is this still the case even if Titles is the only mod you have active? If so, can you link a pastebin of your error log?

**Comment by SuperTiru** [comment]
https://pastebin.com/dna5gkUH
Here you are.
Use curseforge only to use titles mode.
Create a new single world and use the rare title item in creative mode. 
Press t to turn on the title gui, apply the title, and chat. 
Title not applicable.

**Comment by Aurilux** [comment]
Looks like you are still using 3.4.1 (seen at line 36 of that log). Update to 3.4.2 and post the error log after you test that version if it still isn't working.

**Comment by SuperTiru** [comment]
![image](https://user-images.githubusercontent.com/108540864/193635937-2977257d-4977-4c88-aea7-a648d0261dce.png)
I am using the latest version based on curseforge.

**Comment by Aurilux** [comment]
Odd that it's displaying different version numbers, but I have confirmed that display titles aren't being updated properly. Strangely enough it is the same problem I am currently working to solve in the 1.18 version, so it seems it carried over. I am working on it now.
