### ISSUE TITLE
[suggest] Disable an existing title

### ISSUE THREAD

**Issue by SuperTiru** [Aurilux/Titles#37]
I'm a modpack maker.
When the existing title and the newly added title are combined, countless titles are created. Unfortunately, I wanted to solve the problem by deactivating the existing title, but I couldn't deactivate it through datapack.
The work was possible in title 3.3.2 version, but it was confirmed that the work was not possible in the latest version.

**Comment by Aurilux** [comment]
I'm going to need a bit more information. Also, I am confused by the sentence "When the existing title and the newly added title are combined, countless titles are created". Is there some kind of bug that is making infinite titles? If you can provide some pictures, a short video, or an error log (if it is an error causing this), then I can start narrowing it down.

**Comment by SuperTiru** [comment]
No, it wasn't a bug, it was an exaggeration. 
I think there is a misunderstanding because my native language is not English Sorry.
I made several custom titles. However, when the existing title and the number of my title are combined, about 100 titles are created. 
I don't want that many titles, so I want to deactivate some existing titles.

**Comment by Aurilux** [comment]
No worries! You said that you were able to remove them in the 3.3.2 version. How did you it in that version?

**Comment by SuperTiru** [comment]
In that version, if i erased all of the .json files of the datapack with {}, the title did not appear. 
However, in the latest version, replacing the .json files of the data pack with {} does not apply. 
It is even impossible to change the type to command.
I think it's probably because in the latest version, the existing title is applied through 'id'.
