### ISSUE TITLE
[1.18.2] Unlocked Titles reset upon death

### ISSUE THREAD

**Issue by Shibva** [Aurilux/Titles#39]
In the current 1.18.2 release of this mod ive come across a problem where my titles kept disappearing and I was unsure of why

it was yesterday night (or early this morning) that Ive discovered that all titles that I have unlocked Wipe/Reset when I die. 

Using the /titles refresh command appears to fix this but is annoying to do each time I die.

This bug was found/rediscovered while on a 18.2 server where the mod here was recently introduced.

_Originally posted by @Shibva in https://github.com/Aurilux/Titles/issues/16#issuecomment-1493073382_

**Comment by Aurilux** [comment]
Does it also do this when changing dimensions from both the nether and end?

**Comment by Shibva** [comment]
I have not tested this yet; though if using a TPA datapack that allows for dimension teleportation count then I belive its not; though dont quote me on this. Not sure if it counts in this context. I will get back to you later today on this
