### ISSUE TITLE
[1.18.2] FTB Essentials Nickname Compatability / Standalone Nickname functionality

### ISSUE THREAD

**Issue by Geccpls** [Aurilux/Titles#40]
If both FTB Essentials and Titles are installed, and you try to use FTBE's "/nickname" command, FTBE will report that a nickname has been set, but it will not display in game.

It appears Titles takes priority on replacing the character's username. I was wondering if it would be possible to add a check to see if a FTBE nickname has been set, and to use that as the player name instead. 

This appears to be FTBE's implementation of the nickname command for reference: https://github.com/FTBTeam/FTB-Essentials/blob/25b530a417e6424b6fb4697a1e81b1ca91cdeb02/src/main/java/dev/ftb/mods/ftbessentials/command/MiscCommands.java#L81

Edit: Actually, could we just get custom nicknames built into Titles? This would be a much cleaner solution, dunno why I didn't think of it when writing this.

**Comment by Aurilux** [comment]
I am not that familiar with FTB Essentials, so to make sure I understand, the "nickname" command effectively changes the player's display name to something else? For example, I could use the command to set my nickname to BillyJoeBob, becoming my display name while in-game? Also, besides the incompatibility between Titles and FTBE, is there anything else you use Essentials for?

**Comment by Geccpls** [comment]
Yeah, the /nickname command in FTBE would let you change your display name to BillyJoeBob, so any messages you send would be prepended with <BillyJoeBob> instead of <Aurilux>. If you try to do it while Titles is installed, it will not change and keep sending messages as <Aurilux, Title Holder> instead of <BillyJoeBob, Title Holder> which is what I would like to see.

We often use its /home feature as well. I suspect our server admin uses a few of the other commands too. I don't think FTBE is interfering with titles in any way though.

**Comment by Aurilux** [comment]
Added nickname in update 3.5.1

**Comment by Geccpls** [comment]
Thank you so much :) Server admin added this to the to do list immediately haha
