### ISSUE TITLE
Suggestion: Mod Enhancement

### ISSUE THREAD

**Issue by Omegapsychosis** [Aurilux/Titles#5]
I had a few ideas that could really help flesh out this mod. 

User Defined Titles - A way to define titles as a user/modpack maker would be awesome. If this exists and I missed it I am sorry.

Command to award titles - Making a command that could unlock titles would allow modpack makers ways to integrate titles into their pack as questing rewards, using things like BQM.

the command could be something like...

**/title username add title_name**

Gamestages Integration  - a way to assign a title if the player has a certain gamestage would be awesome as well. Especially with a mod like GamestageBooks. One could add title books to dungeon loot for players to seek out.

**Comment by Aurilux** [comment]
All of those are really good suggestions! The command one is easy to figure out, but for the other two (user defined, gamestage), could you list some open source mods that do those so that I can use them for reference? I don't know where to start otherwise.

**Comment by Omegapsychosis** [comment]
For the user defined part you could add a customtitles.json file and place it in a folder under configs.

I know a lot of modders are starting to use JSOn files for customization so asking around on the mod development discord.

https://discordapp.com/invite/EDbExcX

I think the GameStages mod itself has an API that can be used for getting GameStages to work.

https://github.com/Darkhax-Minecraft/Game-Stages

There is a designated section for Mod Support, and if you are unable to get it working I am sure DarkHax would be willing to help if you opened an issue.

I am sorry I can't be of more help than that.

**Comment by Aurilux** [comment]
Thank you. That still gives me a starting point to work from.

**Comment by Aurilux** [comment]
With update 3.0.0 I added the ability for users to define their own titles for use with the Title Archive item. The wiki will tell you how to use it.

As for GameStages: it seems any title they want to put behind a game stage is easily solved by only granting titles when they get to those game stages or quests available in those stages. So for right now there is no explicit game stage integration, but I will revisit later should I see a reason.
