### ISSUE TITLE
Place title below name

### ISSUE THREAD

**Issue by nihiluis** [Aurilux/Titles#6]
I think placing the title below the name and making the font a bit smaller, mimicking other MMOs (WoW, GW2, etc.), would be more visually appealing than the current way (perhaps only for those who would opt-in via config).

Great mod regardless.

**Comment by Aurilux** [comment]
I thought about doing this a while ago, but seemed to require a lot more work than I initially wanted to do. I'll take another look at it because I do agree it would look better.

**Comment by faeldray** [comment]
I don't know if this will help at all but I came across a mod that adds titles under the player's name using name tags. Maybe there's something in their code that you could use to make this feature easier to add?
https://www.curseforge.com/minecraft/mc-mods/entitled

**Comment by Aurilux** [comment]
Coincidentally, I am currently working on this feature. I will take a look and see if that mod can help. I appreciate it!
