### ISSUE TITLE
crash on startup from client

### ISSUE THREAD

**Issue by zEpiixz** [Aurilux/Titles#9]
https://pastebin.com/2TAZMAVz

**Comment by Aurilux** [comment]
I am unable to replicate this. Could you try to start your game with Titles as your only active mod and see if it still crashes?

**Comment by BookerCatch** [comment]
I'm having the same issue. Here is my log without any other mods loaded https://pastebin.com/DYU9GKWC

**Comment by Aurilux** [comment]
Why don't you guys try this out and let me know if it works before I commit to anything.
[Titles-1.12.2-3.1.2.jar.zip](https://github.com/Aurilux/Titles/files/4587528/Titles-1.12.2-3.1.2.jar.zip)

**Comment by BookerCatch** [comment]
Thanks. That seems to have resolved the issue for me. Hopefully you are able to find what is causing the incompatibility with MultiMC. Good luck.
